# Generated by Django 5.2.5 on 2026-03-01 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Photo_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_types', models.CharField(choices=[('Nature', 'Nature'), ('Portrait', 'Portrait'), ('Architecture', 'Architecture'), ('Street', 'Street'), ('Wildlife', 'Wildlife'), ('Abstract', 'Abstract')], max_length=20)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='PhotoApp.photo')),
            ],
        ),
    ]
