# Generated by Django 5.2.5 on 2026-04-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0003_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BigIntegerField(default=1),
        ),
    ]
